name = "api-onlyone"
compatibility_date = "2023-12-01"

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "restaurant-images"
preview_bucket_name = "restaurant-images"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
